packages:
  # board: !include "../distribuzione/a16.yaml"
  base: !include ../../components/base.yaml
  wifi: !include ../../components/wifi.yaml
  slow_pwm_soggiorno: !include
    file: ../../components/dual_pid.yaml
    vars:
      circuit_name: "Soggiorno"
      circuit_slug: "soggiorno"
      output: slow_pwm_soggiorno
      sensor: termometro_soggiorno_temperature
      heat_default_temperature: 28.0
      heat_kp: 0.2
      heat_ki: 0.01
      heat_kd: 0.0
      cool_default_temperature: 22.0
      cool_kp: 0.2
      cool_ki: 0.01
      cool_kd: 0.0
      switch: fake_switch
  slow_pwm_cucina: !include
    file: ../../components/dual_pid.yaml
    vars:
      circuit_name: "Cucina"
      circuit_slug: "cucina"
      output: slow_pwm_cucina
      sensor: termometro_soggiorno_temperature
      heat_default_temperature: 28.0
      heat_kp: 0.2
      heat_ki: 0.01
      heat_kd: 0.0
      cool_default_temperature: 22.0
      cool_kp: 0.2
      cool_ki: 0.01
      cool_kd: 0.0
      switch: fake_switch
  slow_pwm_bagno: !include
    file: ../../components/dual_pid.yaml
    vars:
      circuit_name: "Bagno"
      circuit_slug: "bagno"
      output: slow_pwm_bagno
      sensor: termometro_soggiorno_temperature
      heat_default_temperature: 28.0
      heat_kp: 0.2
      heat_ki: 0.01
      heat_kd: 0.0
      cool_default_temperature: 22.0
      cool_kp: 0.2
      cool_ki: 0.01
      cool_kd: 0.0
      switch: fake_switch
  slow_pwm_anticamera: !include
    file: ../../components/dual_pid.yaml
    vars:
      circuit_name: "Anticamera"
      circuit_slug: "anticamera"
      output: slow_pwm_anticamera
      sensor: termometro_soggiorno_temperature
      heat_default_temperature: 28.0
      heat_kp: 0.2
      heat_ki: 0.01
      heat_kd: 0.0
      cool_default_temperature: 22.0
      cool_kp: 0.2
      cool_ki: 0.01
      cool_kd: 0.0
      switch: fake_switch

uart:
  - id: rs485
    tx_pin: GPIO13
    rx_pin: GPIO16
    baud_rate: 9600

i2c:
  sda: GPIO4
  scl:
    number: GPIO5
    ignore_strapping_warning: true

pcf8574:
  - id: inputs_1_8
    address: 0x22
    pcf8575: false
  - id: inputs_9_16
    address: 0x21
    pcf8575: false
  - id: outputs_1_8
    address: 0x24
    pcf8575: false
  - id: outputs_9_16
    address: 0x25
    pcf8575: false

binary_sensor:
  - platform: gpio
    name: "1-Wire Bus 01"
    id: one_wire_bus_1
    pin:
      number: GPIO32
      inverted: true

  - platform: gpio
    name: "1-Wire Bus 02"
    pin:
      number: GPIO33
      inverted: true

  - platform: gpio
    name: "1-Wire Bus 03"
    pin:
      number: GPIO14
      inverted: true

  - platform: gpio
    name: "Input 01"
    id: input_01
    pin:
      pcf8574: inputs_1_8
      number: 0
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 02"
    id: input_02
    pin:
      pcf8574: inputs_1_8
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 03"
    id: input_03
    pin:
      pcf8574: inputs_1_8
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 04"
    id: input_04
    pin:
      pcf8574: inputs_1_8
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 05"
    id: input_05
    pin:
      pcf8574: inputs_1_8
      number: 4
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 06"
    id: input_06
    pin:
      pcf8574: inputs_1_8
      number: 5
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 07"
    id: input_07
    pin:
      pcf8574: inputs_1_8
      number: 6
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 08"
    id: input_08
    pin:
      pcf8574: inputs_1_8
      number: 7
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 09"
    id: input_09
    pin:
      pcf8574: inputs_9_16
      number: 0
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 10"
    id: input_10
    pin:
      pcf8574: inputs_9_16
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 11"
    id: input_11
    pin:
      pcf8574: inputs_9_16
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 12"
    id: input_12
    pin:
      pcf8574: inputs_9_16
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 13"
    id: input_13
    pin:
      pcf8574: inputs_9_16
      number: 4
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 14"
    id: input_14
    pin:
      pcf8574: inputs_9_16
      number: 5
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 15"
    id: input_15
    pin:
      pcf8574: inputs_9_16
      number: 6
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "Input 16"
    id: input_16
    pin:
      pcf8574: inputs_9_16
      number: 7
      mode: INPUT
      inverted: true

switch:
  - platform: gpio
    name: "Relay 01"
    id: relay_01
    pin:
      pcf8574: outputs_1_8
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 02"
    id: relay_02
    pin:
      pcf8574: outputs_1_8
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 03"
    id: relay_03
    pin:
      pcf8574: outputs_1_8
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 04"
    id: relay_04
    pin:
      pcf8574: outputs_1_8
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 05"
    id: relay_05
    pin:
      pcf8574: outputs_1_8
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 06"
    id: relay_06
    pin:
      pcf8574: outputs_1_8
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 07"
    id: relay_07
    pin:
      pcf8574: outputs_1_8
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 08"
    id: relay_08
    pin:
      pcf8574: outputs_1_8
      number: 7
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 09"
    id: relay_09
    pin:
      pcf8574: outputs_9_16
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 10"
    id: relay_10
    pin:
      pcf8574: outputs_9_16
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 11"
    id: relay_11
    pin:
      pcf8574: outputs_9_16
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 12"
    id: relay_12
    pin:
      pcf8574: outputs_9_16
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 13"
    id: relay_13
    pin:
      pcf8574: outputs_9_16
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 14"
    id: relay_14
    pin:
      pcf8574: outputs_9_16
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 15"
    id: relay_15
    pin:
      pcf8574: outputs_9_16
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "Relay 16"
    id: relay_16
    pin:
      pcf8574: outputs_9_16
      number: 7
      mode: OUTPUT
      inverted: true

  - platform: template
    id: fake_switch
    optimistic: true

sensor:
  - platform: homeassistant
    name: "Temperature Sensor From Home Assistant"
    entity_id: sensor.termometro_soggiorno_temperature
    id: termometro_soggiorno_temperature

output:
  - platform: slow_pwm
    id: slow_pwm_soggiorno
    period: 30s
    turn_on_action:
      - switch.turn_on: relay_07
      - switch.turn_on: relay_06
      - switch.turn_on: relay_05
    turn_off_action:
      - switch.turn_off: relay_07
      - switch.turn_off: relay_06
      - switch.turn_off: relay_05
  - platform: slow_pwm
    id: slow_pwm_cucina
    period: 30s
    turn_on_action:
      - switch.turn_on: relay_01
      - switch.turn_on: relay_02
    turn_off_action:
      - switch.turn_off: relay_01
      - switch.turn_off: relay_02
  - platform: slow_pwm
    id: slow_pwm_bagno
    period: 30s
    turn_on_action:
      - switch.turn_on: relay_03
    turn_off_action:
      - switch.turn_off: relay_03
  - platform: slow_pwm
    id: slow_pwm_anticamera
    period: 30s
    turn_on_action:
      - switch.turn_on: relay_04
    turn_off_action:
      - switch.turn_off: relay_04
