binary_sensor:
  - platform: template
    id: ${sensor_id}_wrapped
    lambda: |-
      return id(${sensor_id});
    internal: true
    on_state:
      then:
        - if:
            condition:
              lambda: "return x;"
            then:
              - logger.log:
                  format: "Direct pump for ${area_name} ON"
              - switch.turn_on: ${relay_id}
            else:
              - logger.log:
                  format: "Direct pump for ${area_name} OFF"
              - switch.turn_off: ${relay_id}
