defaults:
  valve_id: "mixing_valve_${area_name}"
  valve_name: "Mixing Valve for ${area_name}"

packages:
  mixing_valve: !include
    file: mixing_valve.yaml
    vars:
      valve_id: "${valve_id}"
      valve_name: "${valve_name}"
      dallas_address: ${dallas_address}

binary_sensor:
  - platform: packet_transport
    id: ${udp_sensor_id}
    provider: ${udp_provider}
    on_state:
      then:
        - if:
            condition:
              lambda: "return x;"
            then:
              - logger.log:
                  format: "Mixing pump for ${area_name} ON"
              - switch.turn_on: ${relay_id}
            else:
              - logger.log:
                  format: "Mixing pump for ${area_name} OFF"
              - switch.turn_off: ${relay_id}
