packages:
  pid_heat: !include
    file: pid.yaml
    vars:
      mode: "heat"
      circuit_name: ${circuit_name}
      circuit_slug: ${circuit_slug}
      default_temperature: ${heat_default}
      kp: ${heat_kp}
      ki: ${heat_ki}
      kd: ${heat_kd}
  pid_cool: !include
    file: pid.yaml
    vars:
      mode: "cool"
      circuit_name: ${circuit_name}
      circuit_slug: ${circuit_slug}
      default_temperature: ${cool_default}
      kp: ${cool_kp}
      ki: ${cool_ki}
      kd: ${cool_kd}

output:
  - platform: esp32_dac
    pin: ${dac_pin}
    id: dac_${circuit_slug}

switch:
  - platform: gpio
    name: "Pompa Miscelatrice ${circuit_name}"
    id: pump_${circuit_slug}
    pin:
      pcf8574: outputs
      number: ${relay_id}
      mode: OUTPUT
      inverted: true

sensor:
  - platform: dallas_temp
    address: ${sensor_address}
    name: "Temperatura Mandata ${circuit_name}"
    id: temperatura_mandata_${circuit_slug}
    unit_of_measurement: "°C"

climate:
  - id: !extend pid_heat_${circuit_slug}
    heat_output: dac_${circuit_slug}

  - id: !extend pid_cool_${circuit_slug}
    cool_output: dac_${circuit_slug}
