packages:
  board: !include ../boards/a16.yaml
  wifi: !include ../boards/wifi.yaml
  soggiorno: !include ../components/rooms/ground_floor/soggiorno.yaml
  cucina: !include ../components/rooms/ground_floor/cucina.yaml
  bagno: !include ../components/rooms/ground_floor/bagno.yaml
  anticamera: !include ../components/rooms/ground_floor/anticamera.yaml
  sala_pranzo: !include ../components/rooms/ground_floor/sala_pranzo.yaml
  locale_tecnico: !include ../components/rooms/ground_floor/locale_tecnico.yaml

modbus:
  id: rs485_bus
  uart_id: rs485

modbus_controller:
  - id: modbus_0_10v_adapter_fancoils_ground_floor
    address: 0x2
    modbus_id: rs485_bus
    update_interval: 5s

binary_sensor:
  - platform: template
    id: piano_terra_any_radiant_zone_open
    name: "Ground Floor Any Radiant Zone Open"
    device_class: running
    icon: "mdi:pump"
    lambda: |-
      return id(pid_radiant_anticamera).action == climate::CLIMATE_ACTION_HEATING ||
             id(pid_radiant_anticamera).action == climate::CLIMATE_ACTION_COOLING ||
             id(pid_radiant_bagno_terra).action == climate::CLIMATE_ACTION_HEATING ||
             id(pid_radiant_bagno_terra).action == climate::CLIMATE_ACTION_COOLING ||
             id(pid_radiant_cucina).action == climate::CLIMATE_ACTION_HEATING ||
             id(pid_radiant_cucina).action == climate::CLIMATE_ACTION_COOLING ||
             id(pid_radiant_soggiorno).action == climate::CLIMATE_ACTION_HEATING ||
             id(pid_radiant_soggiorno).action == climate::CLIMATE_ACTION_COOLING;

  - platform: template
    id: piano_terra_any_fancoil_zone_open
    name: "Ground Floor Any Fancoil Zone Open"
    device_class: running
    icon: "mdi:pump"
    lambda: |-
      return id(pid_fancoil_cucina).action == climate::CLIMATE_ACTION_HEATING ||
             id(pid_fancoil_cucina).action == climate::CLIMATE_ACTION_COOLING ||
             id(pid_fancoil_sala_pranzo).action == climate::CLIMATE_ACTION_HEATING ||
             id(pid_fancoil_sala_pranzo).action == climate::CLIMATE_ACTION_COOLING ||
             id(pid_fancoil_soggiorno).action == climate::CLIMATE_ACTION_HEATING ||
             id(pid_fancoil_soggiorno).action == climate::CLIMATE_ACTION_COOLING;

script:
  - id: ground_floor_radiant_pump_management
    mode: queued
    then:
      - if:
          condition:
            lambda: |-
              return id(pid_radiant_anticamera).action == climate::CLIMATE_ACTION_HEATING ||
                     id(pid_radiant_anticamera).action == climate::CLIMATE_ACTION_COOLING ||
                     id(pid_radiant_bagno_terra).action == climate::CLIMATE_ACTION_HEATING ||
                     id(pid_radiant_bagno_terra).action == climate::CLIMATE_ACTION_COOLING ||
                     id(pid_radiant_cucina).action == climate::CLIMATE_ACTION_HEATING ||
                     id(pid_radiant_cucina).action == climate::CLIMATE_ACTION_COOLING ||
                     id(pid_radiant_soggiorno).action == climate::CLIMATE_ACTION_HEATING ||
                     id(pid_radiant_soggiorno).action == climate::CLIMATE_ACTION_COOLING;
          then:
            - switch.turn_on: relay_16
          else:
            - switch.turn_off: relay_16
  - id: ground_floor_fancoils_pump_management
    mode: queued
    then:
      - if:
          condition:
            lambda: |-
              return id(pid_fancoil_cucina).action == climate::CLIMATE_ACTION_HEATING ||
                     id(pid_fancoil_cucina).action == climate::CLIMATE_ACTION_COOLING ||
                     id(pid_fancoil_sala_pranzo).action == climate::CLIMATE_ACTION_HEATING ||
                     id(pid_fancoil_sala_pranzo).action == climate::CLIMATE_ACTION_COOLING ||
                     id(pid_fancoil_soggiorno).action == climate::CLIMATE_ACTION_HEATING ||
                     id(pid_fancoil_soggiorno).action == climate::CLIMATE_ACTION_COOLING;
          then:
            - switch.turn_off: relay_15
          else:
            - switch.turn_off: relay_15
