defaults:
  device_name: first-floor-distribution
  friendly_name: "Distribuzione Primo Piano"

packages:
  board: !include ../boards/a16.yaml
  bagno_grande: !include ../components/rooms/first_floor/bagno_grande.yaml
  bagno_ospiti: !include ../components/rooms/first_floor/bagno_ospiti.yaml
  bagno_padronale: !include ../components/rooms/first_floor/bagno_padronale.yaml
  camera_nord: !include ../components/rooms/first_floor/camera_nord.yaml
  camera_sud: !include ../components/rooms/first_floor/camera_sud.yaml
  camera_ospiti: !include ../components/rooms/first_floor/camera_ospiti.yaml
  camera_padronale: !include ../components/rooms/first_floor/camera_padronale.yaml
  lavanderia: !include ../components/rooms/first_floor/lavanderia.yaml
  sottotetto: !include ../components/rooms/second_floor/sottotetto.yaml

udp:
  id: udp_packet_transport

packet_transport:
  - platform: udp
    udp_id: udp_packet_transport
    update_interval: 5s
    binary_sensors:
      - first_floor_any_zone_open
    sensors:
      - first_floor_max_dew_point
    providers:
      - name: room-sensor-bagno-grande
      - name: room-sensor-bagno-ospiti
      - name: room-sensor-bagno-padronale
      - name: room-sensor-camera-nord
      - name: room-sensor-camera-sud
      - name: room-sensor-camera-ospiti
      - name: room-sensor-camera-padronale
      - name: room-sensor-lavanderia
      - name: room-sensor-sottotetto

modbus:
  id: rs485_bus
  uart_id: rs485

modbus_controller:
  - id: modbus_0_10v_adapter_fancoils_second_floor
    address: 0x2
    modbus_id: rs485_bus
    update_interval: 5s

binary_sensor:
  - platform: template
    id: first_floor_any_zone_open
    name: "First Floor Zone Open"
    device_class: running
    icon: "mdi:pump"
    lambda: |-
      return id(pid_radiant_bagno_padronale_is_active)||
             id(pid_radiant_bagno_grande_is_active)||
             id(pid_radiant_bagno_ospiti_is_active)||
             id(pid_radiant_lavanderia_is_active)||
             id(pid_radiant_camera_nord_is_active)||
             id(pid_radiant_camera_sud_is_active)||
             id(pid_radiant_camera_padronale_is_active)||
             id(pid_radiant_camera_ospiti_is_active);
  - platform: template
    id: second_floor_fancoil_any_zone_open
    name: "Second Floor Fancoil Zone Open"
    device_class: running
    icon: "mdi:pump"
    lambda: |-
      return id(pid_fancoil_sottotetto_is_active);

sensor:
  - platform: combination
    id: first_floor_max_dew_point
    name: "Max Dew Point Primo piano"
    type: max
    sources:
      - source: camera_ospiti_dew_point
      - source: camera_nord_dew_point
      - source: camera_padronale_dew_point
      - source: camera_sud_dew_point
