packages:
  base: !include ../boards/a6.yaml
  wifi: !include ../boards/wifi.yaml
  pid_sensor_mixing_ground_floor: !include
    file: ../components/pid_sensors.yaml
    vars:
      pid_id: pid_mixing_ground_floor
      pid_name: "PID Miscelatrice Piano Terra"
  pid_sensors_mixing_first_floor: !include
    file: ../components/pid_sensors.yaml
    vars:
      pid_id: pid_mixing_first_floor
      pid_name: "PID Miscelatrice Primo Piano"

# Modbus RTU bus for 0-10V adapters
modbus:
  id: rs485_bus
  uart_id: rs485

sensor:
  - platform: dallas_temp
    address: 0x81000000b3e6f628
    name: "Dallas 0x81000000b3e6f628"
    id: dallas_0x81000000b3e6f628
    unit_of_measurement: "°C"
    one_wire_id: one_wire_01
  - platform: dallas_temp
    address: 0xe9000000b366ed28
    name: "Temperatura Mandata 0xe9000000b366ed28"
    id: dallas_0xe9000000b366ed28
    unit_of_measurement: "°C"
    one_wire_id: one_wire_01

climate:
  - platform: pid
    id: pid_mixing_ground_floor
    name: "PID Miscelatrice Piano Terra"
    sensor: dallas_0x81000000b3e6f628
    default_target_temperature: 28.0
    heat_output: dac_1
    cool_output: dac_1
    control_parameters:
      kp: 0.2
      ki: 0.01
      kd: 0.0
    visual:
      min_temperature: 0
      max_temperature: 40
      temperature_step: 0.5
    on_state:
      # Relay control: turn on when PID active, off when idle
      - lambda: |-
          if (x.action == climate::CLIMATE_ACTION_HEATING || x.action == climate::CLIMATE_ACTION_COOLING) {
            id(relay_1).turn_on();
          } else {
            id(relay_1).turn_off();
          }

  - platform: pid
    id: pid_mixing_first_floor
    name: "PID Miscelatrice Primo Piano"
    sensor: dallas_0xe9000000b366ed28
    default_target_temperature: 28.0
    heat_output: dac_2
    cool_output: dac_2
    control_parameters:
      kp: 0.2
      ki: 0.01
      kd: 0.0
    visual:
      min_temperature: 0
      max_temperature: 40
      temperature_step: 0.5
    on_state:
      # Relay control: turn on when PID active, off when idle
      - lambda: |-
          if (x.action == climate::CLIMATE_ACTION_HEATING || x.action == climate::CLIMATE_ACTION_COOLING) {
            id(relay_2).turn_on();
          } else {
            id(relay_2).turn_off();
          }
