defaults:
  device_name: gruppo-miscelazione
  friendly_name: "Gruppo Miscelazione"

packages:
  base: !include ../boards/a6.yaml
  wifi: !include ../boards/wifi.yaml
  mixing_pump_radiant_piano_terra: !include
    file: ../components/mixing_pump.yaml
    vars:
      area_slug: "ground_floor_radiant"
      area_name: "Piano Terra"
      dallas_address: 0x81000000b3e6f628
      udp_provider: distribuzione-piano-terra
      udp_sensor_id: piano_terra_any_radiant_zone_open
      relay_id: relay_1
      dac_output: dac_1

  mixing_pump_primo_piano: !include
    file: ../components/mixing_pump.yaml
    vars:
      area_slug: "primo_piano"
      area_name: "Primo Piano"
      dallas_address: 0xe9000000b366ed28
      udp_provider: distribuzione-primo-piano
      udp_sensor_id: any_zone_open_primo_piano
      relay_id: relay_3
      dac_output: dac_2

udp:
  id: udp_packet_transport

packet_transport:
  - platform: udp
    udp_id: udp_packet_transport
    providers:
      - name: distribuzione-piano-terra
      - name: distribuzione-primo-piano

binary_sensor:
  - platform: packet_transport
    id: piano_terra_any_fancoil_zone_open
    provider: distribuzione-piano-terra
    on_state:
      then:
        - if:
            condition:
              lambda: "return x;"
            then:
              - logger.log:
                  format: "Ground Floor Any Fancoil Zone OPEN"
              - switch.turn_on: relay_2
            else:
              - logger.log:
                  format: "Ground Floor Any Fancoil Zone CLOSED"
              - switch.turn_off: relay_2
