packages:
  base: !include ../boards/a6.yaml
  wifi: !include ../boards/wifi.yaml
  pid_terra: !include
    file: ../components/dual_pid.yaml
    vars:
      circuit_name: "Piano Terra"
      circuit_slug: piano_terra
      sensor: dallas_0x81000000b3e6f628
      switch: relay_1
      output: dac_1
      heat_default_temperature: 28.0
      heat_kp: 0.2
      heat_ki: 0.01
      heat_kd: 0.0
      cool_default_temperature: 22.0
      cool_kp: 0.2
      cool_ki: 0.01
      cool_kd: 0.0
  pid_primo: !include
    file: ../../components/dual_pid.yaml
    vars:
      circuit_name: "Primo Piano"
      circuit_slug: primo_piano
      sensor: dallas_0xe9000000b366ed28
      switch: relay_2
      output: dac_2
      heat_default_temperature: 28.0
      heat_kp: 0.2
      heat_ki: 0.01
      heat_kd: 0.0
      cool_default_temperature: 22.0
      cool_kp: 0.2
      cool_ki: 0.01
      cool_kd: 0.0

sensor:
  - platform: dallas_temp
    address: 0x81000000b3e6f628
    name: "Dallas 0x81000000b3e6f628"
    id: dallas_0x81000000b3e6f628
    unit_of_measurement: "°C"
    internal: true
    one_wire_id: one_wire_01
  - platform: dallas_temp
    address: 0xe9000000b366ed28
    name: "Temperatura Mandata 0xe9000000b366ed28"
    id: dallas_0xe9000000b366ed28
    unit_of_measurement: "°C"
    internal: true
    one_wire_id: one_wire_01
