defaults:
  device_name: main-distribution
  friendly_name: "Gruppo Miscelazione"

packages:
  base: !include ../boards/a6.yaml
  wifi: !include ../boards/wifi.yaml
  mixing_pump_ground_floor_radiant: !include
    file: ../components/mixing_pump.yaml
    vars:
      area_slug: "ground_floor_radiant"
      area_name: "Radiante Piano Terra"
      dallas_address: 0x81000000b3e6f628
      udp_provider: ground-floor-distribution
      udp_sensor_id: ground_floor_radiant_zone_open
      relay_id: relay_1
      dac_output: dac_1
  direct_pump_ground_floor_fancoil: !include
    file: ../components/direct_pump.yaml
    vars:
      area_slug: "ground_floor_fancoil"
      area_name: "Fancoil Piano Terra"
      udp_provider: ground-floor-distribution
      udp_sensor_id: ground_floor_fancoil_zone_open
      relay_id: relay_2
  mixing_pump_primo_piano: !include
    file: ../components/mixing_pump.yaml
    vars:
      area_slug: "first_floor_radiant"
      area_name: "Primo Piano"
      dallas_address: 0xe9000000b366ed28
      udp_provider: first-floor-distribution
      udp_sensor_id: first_floor_any_zone_open
      relay_id: relay_3
      dac_output: dac_2
  direct_pump_fancoil_secondo_piano: !include
    file: ../components/direct_pump.yaml
    vars:
      area_slug: "fancoil_second_floor"
      area_name: "Fancoil Secondo Piano"
      udp_provider: second-floor-distribution
      udp_sensor_id: second_floor_fancoil_any_zone_open
      relay_id: relay_4

udp:
  id: udp_packet_transport

packet_transport:
  - platform: udp
    udp_id: udp_packet_transport
    providers:
      - name: ground-floor-distribution
      - name: first-floor-distribution

sensor:
  - platform: packet_transport
    id: first_floor_max_dew_point
    provider: first-floor-distribution
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    on_value:
      then:
        - climate.control:
            id: pid_mixing_valve_first_floor_radiant
            target_temperature: !lambda "return (x + 1);"
