esphome:
  name: ${device_name}
  min_version: 2026.2.0
  friendly_name: ${friendly_name}

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: ${encryption_key}

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

i2c:
  id: i2c_bus
  sda: GPIO5
  scl: GPIO6
  scan: true

sensor:
  - platform: sht4x
    temperature:
      name: "SHT45 Temperature"
    humidity:
      name: "SHT45 Humidity"
  - platform: sen6x
    temperature:
      name: "SEN6x Temperature"
      accuracy_decimals: 2
    humidity:
      name: "SEN6x Humidity"
      accuracy_decimals: 2
    pm_1_0:
      name: PM <1µm Weight concentration
      accuracy_decimals: 2
    pm_2_5:
      name: PM <2.5µm Weight concentration
      accuracy_decimals: 2
    pm_4_0:
      name: PM <4µm Weight concentration
      accuracy_decimals: 2
    pm_10_0:
      name: PM <10µm Weight concentration
      accuracy_decimals: 2
    nox:
      name: NOx
    voc:
      name: VOC
    co2:
      name: Carbon Dioxide