# =============================================================================
# Node: node101 — ID 101
# =============================================================================
# Floor:    Ground
# Location: Ground floor living room
# Room:     8, Board: 0
# Buttons:  2 (GPIO 20,21)
# CAN ID:   Input  = 0x265
#            Status = 0x665
# =============================================================================

substitutions:
        node_name: "node101"
        node_id: "101"
        room_id: "8"
        board_id: "0"
        output_can_id: "0x465"
        status_can_id: "0x665"
        debounce_ms: "50"
        can_cs_pin: "GPIO9"
        can_clk_pin: "GPIO2"
        can_mosi_pin: "GPIO3"
        can_miso_pin: "GPIO4"
        can_int_pin: "GPIO11"
        can_clock: "16MHZ"

esphome:
  name: ${node_name}
  friendly_name: "Ground floor living room"

rp2040:
  board: rpipico

logger:
  level: DEBUG

packages:
  base: !include ../common/base_node.yaml
  btn0: !include { file: ../common/button.yaml, vars: { button_index: "0", button_gpio: "20" } }
  btn1: !include { file: ../common/button.yaml, vars: { button_index: "1", button_gpio: "21" } }
