#!/usr/bin/env bash
# =============================================================================
# ci-dummy-secrets.sh — generate placeholder secrets for CI validation builds.
#
# ESPHome resolves `!secret` against the secrets.yaml in the MAIN config's
# directory, so every directory that hosts an entry point (devices/,
# devices/locals/) gets a copy. Keys must be format-valid (the API encryption
# key is checked for base64/32-byte length at config time) but are never real:
# CI only validates and compiles, it never talks to a device.
#
# Keep the key list in sync with devices/secrets.yaml.example.
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DUMMY_KEY="$(openssl rand -base64 32)"

for dir in "$REPO_ROOT/devices" "$REPO_ROOT/devices/locals"; do
  # Never clobber a developer's real (gitignored) secrets — only CI, or an
  # explicit FORCE_DUMMY_SECRETS=1, may overwrite an existing file.
  if [ -f "$dir/secrets.yaml" ] && [ "${CI:-}" != "true" ] && [ "${FORCE_DUMMY_SECRETS:-}" != "1" ]; then
    echo "refusing to overwrite existing $dir/secrets.yaml (set FORCE_DUMMY_SECRETS=1 to force)" >&2
    exit 1
  fi
  cat > "$dir/secrets.yaml" <<EOF
# GENERATED by scripts/ci-dummy-secrets.sh — CI placeholders, not real secrets.
wifi_ssid: "ci-dummy-ssid"
wifi_password: "ci-dummy-password"
wifi_hotspot_pass: "ci-dummy-hotspot"
api_encryption_key: "$DUMMY_KEY"
health_monitor_encryption_key: "$DUMMY_KEY"
encryption_key: "$DUMMY_KEY"
ota_password: "ci-dummy-ota-password"
github_username: "ci-dummy-user"
github_pat: "ghp_cidummytoken"
EOF
done

echo "dummy secrets written to devices/secrets.yaml and devices/locals/secrets.yaml"
